# Use postgres/postgres user/password credentials
version: '3.4'

services:
  db:
    image: postgres:latest
    restart: always
    # REMOVE PORTS FOR PROD
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ft_transcendance
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./templates:/etc/nginx/templates
      - avatars:/usr/share/nginx/avatars
    ports:
      - 80:80
      - 443:443

  app:
    build:
      context: app
      network: host
    depends_on:
      - db
    restart: always
    volumes:
      - avatars:/srv/avatars
    env_file:
      - .env

  front:
    build:
      context: front
      network: host
      args:
        - REACT_APP_API42UID=${REACT_APP_API42UID}
    restart: always
    env_file:
      - .env

volumes:
  pgdata:
  avatars:
